<a href="https://colab.research.google.com/github/Ankit-Vishvakarma/K-Nearest-Neighbour-Algorithm/blob/main/K_Nearest_Neighbour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
df = pd.read_csv('fruit_dataset.csv')

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   fruit_label  59 non-null     int64  
 1   fruit_name   59 non-null     object 
 2   mass         59 non-null     int64  
 3   width        59 non-null     float64
 4   height       59 non-null     float64
 5   color_score  59 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.9+ KB


fruit_label fruit_name  mass  width  height  color_score
0            1      apple   192    8.4     7.3         0.55
1            1      apple   180    8.0     6.8         0.59
2            1      apple   176    7.4     7.2         0.60
3            2   mandarin    86    6.2     4.7         0.80
4            2   mandarin    84    6.0     4.6         0.79

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
X=df[['mass','width','height']]
Y=df['fruit_label']
X

mass  width  height
0    192    8.4     7.3
1    180    8.0     6.8
2    176    7.4     7.2
3     86    6.2     4.7
4     84    6.0     4.6
5     80    5.8     4.3
6     80    5.9     4.3
7     76    5.8     4.0
8    178    7.1     7.8
9    172    7.4     7.0
10   166    6.9     7.3
11   172    7.1     7.6
12   154    7.0     7.1
13   164    7.3     7.7
14   152    7.6     7.3
15   156    7.7     7.1
16   156    7.6     7.5
17   168    7.5     7.6
18   162    7.5     7.1
19   162    7.4     7.2
20   160    7.5     7.5
21   156    7.4     7.4
22   140    7.3     7.1
23   170    7.6     7.9
24   342    9.0     9.4
25   356    9.2     9.2
26   362    9.6     9.2
27   204    7.5     9.2
28   140    6.7     7.1
29   160    7.0     7.4
30   158    7.1     7.5
31   210    7.8     8.0
32   164    7.2     7.0
33   190    7.5     8.1
34   142    7.6     7.8
35   150    7.1     7.9
36   160    7.1     7.6
37   154    7.3     7.3
38   158    7.2     7.8
39   144    6.8     7.4
40   154    7.1     7.5
41   180    7.6     8.2
42   154    7.2     7.2
43   194    7.2    10.3
44   200    7.3    10.5
45   186    7.2     9.2
46   216    7.3    10.2
47   196    7.3     9.7
48   174    7.3    10.1
49   132    5.8     8.7
50   130    6.0     8.2
51   116    6.0     7.5
52   118    5.9     8.0
53   120    6.0     8.4
54   116    6.1     8.5
55   116    6.3     7.7
56   116    5.9     8.1
57   152    6.5     8.5
58   118    6.1     8.1

In [ ]:
Y

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size = .20,random_state=0)
X_train.shape  #(47,3)
X_test.shape   #(12,3)
y_train.shape  #(47,)
y_test.shape   #(12,)

(12,)

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski')

knn.fit(X_train,y_train)


KNeighborsClassifier()

In [ ]:
import numpy as np

y_pred = knn.predict(X_test)
y_pred

array([3, 1, 4, 4, 1, 1, 3, 3, 1, 4, 2, 1])

**#Lets make predictions with new data:**

In [ ]:
prediction1=knn.predict([['100','6.3','8']])  # new mass, width,height
prediction1    #output is lemon (4)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([4])

In [ ]:
prediction2=knn.predict([['300','7','10']])
prediction2   #output is orange (3)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([3])

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy is",accuracy_score(y_test, y_pred))

Accuracy is 0.5833333333333334
